# Generated by Django 3.0.8 on 2020-08-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fristname', models.CharField(default=True, max_length=50, null=True)),
                ('lastname', models.CharField(default=True, max_length=50, null=True)),
                ('email', models.CharField(default=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(default=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(default=True, max_length=50, null=True)),
                ('desc', models.TextField(default=True, max_length=500, null=True)),
                ('f_img', models.ImageField(default=True, null=True, upload_to='Blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=50, null=True)),
                ('rating', models.IntegerField(default=True, null=True)),
                ('location', models.CharField(default=True, max_length=100, null=True)),
                ('mobile', models.CharField(default=True, max_length=15, null=True, unique=True)),
                ('time', models.CharField(default=True, max_length=20, null=True)),
                ('category', models.CharField(default=True, max_length=20, null=True)),
                ('license_no', models.CharField(default=True, max_length=20, null=True)),
                ('passwd', models.CharField(default=True, max_length=20, null=True)),
                ('img', models.ImageField(default=True, null=True, upload_to='vendors')),
            ],
        ),
    ]
