# Generated by Django 3.0.8 on 2020-08-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200821_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='email',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='fristname',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='lastname',
        ),
    ]
