# Generated by Django 3.0.8 on 2020-08-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200821_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shaadi',
            field=models.BooleanField(default=False),
        ),
    ]
