# Generated by Django 3.0.8 on 2020-08-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_vendor_shaadi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='shaadi',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
    ]
