# Generated by Django 3.0.8 on 2020-08-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200822_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='shaadi',
            field=models.BooleanField(default=False),
        ),
    ]
