# Generated by Django 3.0.8 on 2020-08-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200822_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='heading',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
