# Generated by Django 3.1.1 on 2020-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_blog_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='reward',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
